services:
  watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      restart: always
      volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'

  portainer-ce:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - '8000:8000'
      - '9000:9000'
    volumes:
      - /home/pi/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock

  emqx:
    image: emqx
    container_name: emqx
    restart: always
    ports:
      - '18083:18083'
      - '1883:1883'
    volumes:
      - /home/pi/emqx/data/iot-emqx-data:/opt/emqx/data
      - /home/pi/emqx/data/iot-emqx-etc:/opt/emqx/etc
      - /home/pi/emqx/data/iot-emqx-log:/opt/emqx/log